### ISSUE TITLE
get_delegate_lock_info 返回字段信息处理

### ISSUE THREAD

**Issue by JW-Zhang001** [platonists/platon.py#2] opened 2022-08-25 10:46 UTC
* Version: 1.3.2
* Python: 3.9
* OS: osx

### What was wrong?

lock_info = normal_aide0.delegate.get_delegate_lock_info(normal_aide0_nt.del_addr)
lock_info: DelegateInfo({'Locks': [{'Epoch': 3, 'Released': '0x0', 'RestrictingPlan': '0x17da3a04c7b3e00000'}], 'Released': 0, 'RestrictingPlan': 0})

### How can it be fixed?
Locks 中嵌套字段未作处理， hex_to_int

**Comment by shinnng** [comment] 2022-08-26 03:09
tks for you issue, it caused by an incorrect API documentation and fixed now.

**Closed by shinnng** 2022-08-26 03:09 UTC
Labels: bug
